my_sa_name                  = "nikolaysherginsa"
#deploy_location             = ""
rg_name                     = "terrafom_traing_rg"
my_account_tier             = "Standard"
my_account_replication_type = "LRS"